version: '3.8'
services:
  cpuminer-multi:
    build:
      context: .
      args:
        # TODO other coin
        COIN: "cpuchain"
    image: "innovanon/cpuminer-multi:${DOCKER_TAG}"
    deploy:
      mode: replicated
      replicas: 1
      update-delay: 91s
      #placement:
      #  constraints: [node.role == worker]

