version: '3.8'
services:
  cpuminer-neoscrypt:
    build:
      context: .
      args:
        # TODO other coin
        COIN: "neoscrypt"
    image: "innovanon/cpuminer-neoscrypt:${DOCKER_TAG}"
    deploy:
      mode: replicated
      replicas: 1
      update-delay: 91s
      #placement:
      #  constraints: [node.role == worker]

