version: '3.8'
services:
  moneroocean:
    build:
      context: .
      args:
        # TODO other coin
        COIN: "xmr"
    image: "innovanon/moneroocean:${DOCKER_TAG}"
    deploy:
      mode: replicated
      replicas: 1
      #update-delay: 10s
      placement:
        constraints: [node.role == worker]

