version: '2.1'
orbs:
  shellcheck: circleci/shellcheck@2.2.2
workflows:
  my_workflow:
    jobs:
      - shellcheck/check:
          dir: .
      - deploy

jobs:
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Push to Upstream
          command: |
            # TODO
            #
