version: '2.1'
orbs:
  shellcheck: circleci/shellcheck@2.2.2
workflows:
  my_workflow:
    jobs:
      - shellcheck/check:
          dir: .
          external_sources: false
          format: checkstyle
          severity: style
      - deploy

jobs:
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Push to Upstream
          command: |
            #curl --user ${CIRCLE_API_USER_TOKEN}:                \
            #     --data build_parameters[CIRCLE_JOB]=build_conan \
            #     --data revision=$CIRCLE_SHA1                    \
            #     https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH

